### ISSUE TITLE
HttpClientExtensions Duplicate

### ISSUE THREAD

**Issue by meron1122** [DuendeArchive/IdentityModel#129]
Hi, Why HttpClientExtensions is duplicate of microsoft class?
That gives me compilation errors and In my opinion bad practice.
> The type 'HttpClientExtensions' exists in both 'IdentityModel, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null' and 'System.Net.Http.Formatting, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by leastprivilege** [comment]
There's always a chance that two classes have the same name. That's why namespaces exist.

**Comment by Carko** [comment]
This issues still exists.

That's why namespaces exist, yes, but then why are there classes inside System.Net.Http namespace in this project?

**Comment by jodegreef** [comment]
Unfortunately namespaces are not used properly here

**Comment by leastprivilege** [comment]
I think this is fixed in v4 preview.
